-- 코드를 작성해주세요
SELECT ID
FROM ECOLI_DATA C
WHERE EXISTS (
    SELECT 1
    FROM ECOLI_DATA P
    WHERE C.PARENT_ID = P.ID AND 
    EXISTS (
        SELECT F.ID
        FROM ECOLI_DATA F
        WHERE P.PARENT_ID = F.ID AND F.PARENT_ID IS NULL
    )
)
ORDER BY C.ID