-- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
    SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES,
    ROW_NUMBER() OVER(
        PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC
    ) AS RN
    FROM REST_INFO
) F
WHERE RN = 1
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC;