-- 코드를 입력하세요
WITH TOTAL AS (
    SELECT COUNT(*) AS COUNT
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021'
)

SELECT YEAR(O.SALES_DATE) AS YEAR, 
       MONTH(O.SALES_DATE) AS MONTH,
       COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS,
       ROUND((COUNT(DISTINCT O.USER_ID) / T.COUNT), 1) AS PUCHASED_RATIO
FROM USER_INFO U
INNER JOIN ONLINE_SALE O
ON U.USER_ID = O.USER_ID
CROSS JOIN TOTAL T
WHERE YEAR(U.JOINED) = '2021'
GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE)

