SELECT YEAR(OS.SALES_DATE) AS YEAR,
MONTH(OS.SALES_DATE) AS MONTH,
COUNT(DISTINCT OS.USER_ID) AS PURCHASED_USERS,
ROUND((COUNT(DISTINCT OS.USER_ID)/(
            SELECT COUNT(*)
            FROM USER_INFO
            WHERE YEAR(JOINED) = '2021'
            GROUP BY YEAR(JOINED)
        )), 1) AS PUCHASED_RATIO
FROM USER_INFO UI
INNER JOIN ONLINE_SALE OS
ON UI.USER_ID = OS.USER_ID
WHERE YEAR(UI.JOINED) = '2021'
GROUP BY MONTH(OS.SALES_DATE), YEAR(OS.SALES_DATE)
ORDER BY 1, 2
