WITH RECURSIVE GEN AS (
    SELECT ID, PARENT_ID, 1 AS GE
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, G.GE + 1 AS GE
    FROM ECOLI_DATA E
    INNER JOIN GEN G
    ON G.ID = E.PARENT_ID
)

SELECT COUNT(*) AS COUNT, GE AS GENERATION
FROM GEN G
WHERE NOT EXISTS (
    SELECT 1
    FROM ECOLI_DATA C
    WHERE C.PARENT_ID = G.ID
)
GROUP BY GE