-- 코드를 작성해주세요
WITH RECURSIVE GEN AS (
    SELECT ID, 1 AS GENERATION, PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT D.ID, G.GENERATION + 1, D.PARENT_ID
    FROM GEN G
    JOIN ECOLI_DATA D
    ON G.ID = D.PARENT_ID
)

SELECT COUNT(*) AS COUNT, G.GENERATION
FROM GEN G
LEFT JOIN ECOLI_DATA E
ON G.ID = E.PARENT_ID
WHERE E.ID IS NULL
GROUP BY G.GENERATION
ORDER BY G.GENERATION;