WITH RECURSIVE GEN AS (
    SELECT 1 AS GENERATION, ID, PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT G.GENERATION + 1, E.ID, E.PARENT_ID
    FROM GEN G
    JOIN ECOLI_DATA E
    ON G.ID = E.PARENT_ID
)

SELECT COUNT(*) AS COUNT, G.GENERATION
FROM GEN G
WHERE NOT EXISTS (
    SELECT 1
    FROM ECOLI_DATA E
    WHERE G.ID = E.PARENT_ID
)
GROUP BY G.GENERATION
ORDER BY G.GENERATION