WITH DURATION AS (
    SELECT
        HISTORY_ID,
        CAR_ID,
        (DATEDIFF(END_DATE, START_DATE) + 1) AS DU,
        CASE
            WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 90 THEN '90일 이상'
            WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 30 THEN '30일 이상'
            WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 7  THEN '7일 이상'
            ELSE NULL
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)
SELECT
    D.HISTORY_ID,
    FLOOR(
        D.DU * C.DAILY_FEE * (100 - IFNULL(P.DISCOUNT_RATE, 0)) / 100
    ) AS FEE
FROM DURATION D
JOIN CAR_RENTAL_COMPANY_CAR C
  ON D.CAR_ID = C.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
  ON P.CAR_TYPE = C.CAR_TYPE
 AND P.DURATION_TYPE = D.DURATION_TYPE
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, D.HISTORY_ID DESC;