-- 코드를 입력하세요
WITH RECURSIVE TIME AS (
    SELECT 0 AS TIME
    
    UNION ALL
    
    SELECT TIME + 1 AS TIME
    FROM TIME
    WHERE TIME < 23
)

SELECT T.TIME AS HOUR, COUNT(O.DATETIME) AS COUNT
FROM ANIMAL_OUTS O
RIGHT OUTER JOIN TIME T
ON HOUR(O.DATETIME) = T.TIME
GROUP BY T.TIME
ORDER BY 1;