SELECT
    H.HOUR,
    COUNT(O.ANIMAL_ID) AS COUNT
FROM (
    SELECT @h := @h + 1 AS HOUR
    FROM (SELECT 0 UNION ALL SELECT 0 UNION ALL SELECT 0 UNION ALL SELECT 0 UNION ALL SELECT 0) a,
         (SELECT 0 UNION ALL SELECT 0 UNION ALL SELECT 0 UNION ALL SELECT 0 UNION ALL SELECT 0) b,
         (SELECT @h := -1) init
    LIMIT 24
) H
LEFT JOIN ANIMAL_OUTS O
    ON H.HOUR = HOUR(O.DATETIME)
GROUP BY H.HOUR
ORDER BY H.HOUR;