-- 코드를 작성해주세요
WITH FE AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)

SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
WHERE EXISTS (
    SELECT 1
    FROM FE F
    WHERE (D.SKILL_CODE & F.CODE) > 0
)
ORDER BY 1
