-- 코드를 입력하세요
WITH X AS(
SELECT MEMBER_ID,RANK() OVER(ORDER BY COUNT(MEMBER_ID) DESC) AS X_COUNT
FROM REST_REVIEW GROUP BY MEMBER_ID

)

SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE 
FROM MEMBER_PROFILE AS M INNER JOIN X USING(MEMBER_ID) JOIN REST_REVIEW AS R ON M.MEMBER_ID =R.MEMBER_ID
WHERE X_COUNT =1 ORDER BY REVIEW_DATE, REVIEW_TEXT
# WITH ranked AS (
#   SELECT
#     MEMBER_ID,
#     RANK() OVER (ORDER BY COUNT(*) DESC) AS rn
#   FROM REST_REVIEW
#   GROUP BY MEMBER_ID
# )
# SELECT
#   P.MEMBER_NAME,
#   R.REVIEW_TEXT,
#   R.REVIEW_DATE
# FROM ranked x
# JOIN MEMBER_PROFILE P
#   ON P.MEMBER_ID = x.MEMBER_ID
# JOIN REST_REVIEW R
#   ON R.MEMBER_ID = x.MEMBER_ID
# WHERE x.rn = 1
# ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;



# SELECT P.MEMBER_NAME, R.REVIEW_TEXT, R.REVIEW_DATE
# FROM MEMBER_PROFILE P
# INNER JOIN 
# (
#     SELECT MEMBER_ID, 
#     RANK() OVER(
#         ORDER BY COUNT(*) DESC
#     ) AS RN,
#     REVIEW_TEXT,
#     REVIEW_DATE
#     FROM REST_REVIEW 
#     GROUP BY MEMBER_ID
#     HAVING RN = 1
# ) R
# ON P.MEMBER_ID = R.MEMBER_ID