-- 코드를 입력하세요
SELECT MONTH(H.START_DATE) AS MONTH, H.CAR_ID, COUNT(1) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
WHERE H.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
AND (
    SELECT COUNT(*)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H2
    WHERE H.CAR_ID = H2.CAR_ID 
        AND H2.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY H2.CAR_ID
) >= 5
GROUP BY MONTH(H.START_DATE), H.CAR_ID
ORDER BY 1, 2 DESC
