-- 코드를 작성해주세요
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
(
    SELECT MAX(E1.SIZE_OF_COLONY)
    FROM ECOLI_DATA E1
    WHERE YEAR(E1.DIFFERENTIATION_DATE) = YEAR(E2.DIFFERENTIATION_DATE)
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) - E2.SIZE_OF_COLONY AS YEAR_DEV, E2.ID
FROM ECOLI_DATA E2
ORDER BY 1, 2;