# -- 코드를 작성해주세요
SELECT T.SCORE, HE.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
FROM (
    SELECT SUM(G.SCORE) AS SCORE, ROW_NUMBER() OVER (ORDER BY SUM(G.SCORE) DESC) AS RN, E.EMP_NO
    FROM HR_EMPLOYEES E
    INNER JOIN HR_GRADE G
    ON E.EMP_NO = G.EMP_NO
    GROUP BY E.EMP_NO
) T
INNER JOIN HR_EMPLOYEES HE
ON T.EMP_NO = HE.EMP_NO
WHERE RN = 1