-- 코드를 입력하세요
SELECT GB.TITLE, GR.BOARD_ID, GR.REPLY_ID, GR.WRITER_ID, GR.CONTENTS, DATE_FORMAT(GR.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_BOARD GB
INNER JOIN USED_GOODS_REPLY GR
ON GB.BOARD_ID = GR.BOARD_ID
WHERE YEAR(GB.CREATED_DATE) = 2022 AND MONTH(GB.CREATED_DATE) = 10
ORDER BY GR.CREATED_DATE ASC, GB.TITLE ASC;