SELECT
  COUNT(*) AS FISH_COUNT,
  MAX(CASE WHEN F.`LENGTH` <= 10 THEN 10 ELSE F.`LENGTH` END) AS MAX_LENGTH,
  F.FISH_TYPE
FROM FISH_INFO F
GROUP BY F.FISH_TYPE
HAVING AVG(CASE WHEN F.`LENGTH` <= 10 THEN 10 ELSE F.`LENGTH` END) >= 33
ORDER BY F.FISH_TYPE;